[package]
name = "glue"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
whodis = { path = "../whodis" }
serde = { workspace = true }
serde_json = "1.0.140"
tsify-next = "0.5.5"
